# Generated by Django 5.1.7 on 2025-04-14 03:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="message",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="留言人")),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                ("content", models.TextField(verbose_name="留言内容")),
                (
                    "created_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="留言时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "留言管理   ",
                "verbose_name_plural": "留言管理",
            },
        ),
    ]
