# Generated by Django 5.1.7 on 2025-04-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("name", models.CharField(max_length=100, verbose_name="作者")),
            ],
            options={
                "verbose_name": "博客类别管理",
                "verbose_name_plural": "博客类别管理",
            },
        ),
    ]
