# Generated by Django 5.1.7 on 2025-04-10 11:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_articletype_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("content", models.CharField(max_length=1000, verbose_name="内容")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="article/", verbose_name="文章图片"
                    ),
                ),
                ("reads", models.IntegerField(default=0, verbose_name="阅读量")),
                ("abstract", models.CharField(max_length=300, verbose_name="摘要")),
                (
                    "create_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="article.articletype",
                        verbose_name="帖子类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "博客帖子管理",
                "verbose_name_plural": "博客帖子管理",
            },
        ),
    ]
