# Generated by Django 5.1.7 on 2025-04-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_alter_article_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(default="draft", max_length=20),
        ),
    ]
