# Generated by Django 5.1.7 on 2025-04-21 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Myconcerns",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="关注时间"),
                ),
                (
                    "concern_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concerned_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关注的用户",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
        ),
    ]
