# Generated by Django 5.1.7 on 2025-05-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myuser",
            options={"verbose_name": "用户表", "verbose_name_plural": "用户表"},
        ),
        migrations.AlterModelTable(
            name="myuser",
            table="t_user",
        ),
    ]
