# Generated by Django 5.1.7 on 2025-05-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_myuser_options_alter_myuser_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="myuser",
            table="t_Myuser_table",
        ),
    ]
