# Generated by Django 5.2.6 on 2025-09-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_myuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='images\\hui.png', null=True, upload_to='avatar/', verbose_name='头像'),
        ),
    ]
