# Generated by Django 5.2.6 on 2025-09-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, default='media\x07vatar\\屏幕截图_2025-05-06_221514_USm9a9e.png', null=True, upload_to='avatar/', verbose_name='头像'),
        ),
    ]
